### ISSUE TITLE
Inbox for chat conversations

### ISSUE THREAD

**Issue by kamyh** [ice-blaze/talent-linker#149]
With unread message indication

**Comment by kamyh** [comment]
I'm not sure how to get all user that have a conversation with a certain user.

for now I've written:

```
$user = User::find(Auth::user()->id);
        $chatsTalkTo = ChatUser::where('sender_id','=',$user->id)->distinct('reciever_id')->get()->pluck('reciever_id');
        $chatsTalkFrom = ChatUser::where('reciever_id','=',$user->id)->distinct('sender_id')->get()->pluck('sender_id');

        $chats = $chatsTalkFrom->merge($chatsTalkTo)->unique();

        echo $chats->flatten();
```

someone have a better idea ?

**Comment by MichaelCaraccio** [comment]
Multiple where clause is a solution : 

$query->where([
    ['column_1', '=', 'value_1'],
    ['column_2', '=', 'value_2'],
    [COLUMN, OPERATOR, VALUE],
    ...
])

**Comment by kamyh** [comment]
I'll test it.

The idea is to get all user id with who you have talk or that have talk to you.

**Comment by kamyh** [comment]
My code works but i m not sure it's the best way.

**Comment by kamyh** [comment]
rah it's a pain in the a*s to have the conversation sorted by the last updated message
