### ISSUE TITLE
Empty view when user have no invitations

### ISSUE THREAD

**Issue by MichaelCaraccio** [ice-blaze/talent-linker#86]
1. We can hide the "invitations" button in user profile

![screen shot 2016-11-09 at 15 42 57](https://cloud.githubusercontent.com/assets/7326386/20142024/5c2e0ca6-a693-11e6-9f43-034e0812607f.png)

2. Display some text when there's no invitation. We can suggest the user to find a project (and we give him a link)

![screen shot 2016-11-09 at 15 43 03](https://cloud.githubusercontent.com/assets/7326386/20142028/60612fe2-a693-11e6-9d54-25ac041c2f0c.png)

**Comment by ice-blaze** [comment]
I would say it's a bug.
