### ISSUE TITLE
Disable scroll on the map

### ISSUE THREAD

**Issue by MichaelCaraccio** [ice-blaze/talent-linker#90]
It's very annoying when you scroll down the page, and you get stuck on the map.

If the user need to zoom-in or zoom-out, maybe we need to display some buttons on the map.

![screen shot 2016-11-09 at 16 02 13](https://cloud.githubusercontent.com/assets/7326386/20142641/efc6f7dc-a695-11e6-8230-b71cf93f6b79.png)

**Comment by ice-blaze** [comment]
It is, but it's also nice to have while searching a place. The best solution would be: zoom-scroll is only activated when the mouse was more than ~2 seconds on the map. Isn't it ?

**Comment by MichaelCaraccio** [comment]
Yes we can try this and see if we find it usefull or not.
