### ISSUE TITLE
Send empty message to someone

### ISSUE THREAD

**Issue by MichaelCaraccio** [ice-blaze/talent-linker#91]
Instead of display a "the content field is required", we can disable the "send" button if the user did not write something on the input.

We can do it by implementing a javascript listener on the input.

![screen shot 2016-11-09 at 16 08 19](https://cloud.githubusercontent.com/assets/7326386/20142893/ec40e7ac-a696-11e6-97ba-82adc50be9e8.png)

**Comment by ice-blaze** [comment]
Agreed
